In [4]:
import pandas as pd
import numpy as np

In [5]:
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [6]:
from sklearn.cluster import KMeans

In [7]:
import warnings
warnings.filterwarnings("ignore")

In [8]:
scaler = StandardScaler()
model = RandomForestClassifier(n_estimators=100, random_state=42)

In [9]:
def preprocess_data(df):
    df = df.copy()

In [12]:
df=pd.read_csv("datasetp.csv")
df

,timestamp,user_id,user_role,ip_address,geo_location,device_type,os,login_status,failed_attempts,session_duration_sec,accessed_resource,data_transfer_mb,request_frequency,unusual_time_access,vpn_used,threat_signature,risk_score,label
0,2026-04-19 06:08:48.816559,U5135,guest,170.110.165.24,Tokyo-Japan,desktop,Android,failed,10,54,api_gateway,76.21,87,1,yes,sql_injection,100,anomaly
1,2026-04-19 06:08:50.816559,U3829,admin,141.202.123.121,Mumbai-India,mobile,Windows,success,2,139,api_gateway,15.07,6,0,no,normal,16,normal
2,2026-04-19 06:09:06.816559,U2926,admin,41.216.198.169,Pune-India,mobile,Linux,success,1,596,user_data,19.66,7,1,no,normal,32,normal
3,2026-04-19 06:08:57.816559,U3058,employee,41.46.11.1,Berlin-Germany,server,Linux,failed,1,528,db_server,12.41,27,0,no,normal,20,normal
4,2026-04-19 06:09:20.816559,U1295,admin,207.203.180.157,Delhi-India,server,Windows,success,0,83,api_gateway,9.56,8,1,no,normal,25,normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2026-04-19 06:58:33.816559,U6244,admin,235.238.80.33,NY-USA,server,Android,failed,8,8,internal_dashboard,99.97,128,1,yes,sql_injection,100,anomaly
996,2026-04-19 07:31:48.816559,U7838,employee,73.40.208.192,NY-USA,desktop,Android,failed,1,494,internal_dashboard,17.24,7,0,no,normal,11,normal
997,2026-04-19 08:21:44.816559,U8796,employee,238.153.155.35,Mumbai-India,server,iOS,failed,2,320,payment_system,4.45,5,1,no,normal,33,normal
998,2026-04-19 06:25:26.816559,U4454,admin,73.52.106.0,Pune-India,server,iOS,success,1,359,user_data,8.21,8,0,yes,normal,30,normal
999,2026-04-19 07:48:42.816559,U6812,employee,156.4.2.61,Mumbai-India,mobile,Linux,failed,8,45,api_gateway,194.64,104,1,yes,brute_force,100,anomaly

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   timestamp             1000 non-null   str
 1   user_id               1000 non-null   str
 2   user_role             1000 non-null   str
 3   ip_address            1000 non-null   str
 4   geo_location          1000 non-null   str
 5   device_type           1000 non-null   str
 6   os                    1000 non-null   str
 7   login_status          1000 non-null   str
 8   failed_attempts       1000 non-null   int64
 9   session_duration_sec  1000 non-null   int64
 10  accessed_resource     1000 non-null   str
 11  data_transfer_mb      1000 non-null   float64
 12  request_frequency     1000 non-null   int64
 13  unusual_time_access   1000 non-null   int64
 14  vpn_used              1000 non-null   str
 15  threat_signature      1000 non-null   str
 16  risk_score            1000 non-null   int64
 17  label                 1000 non-null   str
dtypes: float64(1), int64(5), str(12)
memory usage: 245.3 KB

In [15]:
df.isna().sum()

timestamp               0
user_id                 0
user_role               0
ip_address              0
geo_location            0
device_type             0
os                      0
login_status            0
failed_attempts         0
session_duration_sec    0
accessed_resource       0
data_transfer_mb        0
request_frequency       0
unusual_time_access     0
vpn_used                0
threat_signature        0
risk_score              0
label                   0
dtype: int64

In [16]:
df.fillna(0, inplace=True)

,timestamp,user_id,user_role,ip_address,geo_location,device_type,os,login_status,failed_attempts,session_duration_sec,accessed_resource,data_transfer_mb,request_frequency,unusual_time_access,vpn_used,threat_signature,risk_score,label
0,2026-04-19 06:08:48.816559,U5135,guest,170.110.165.24,Tokyo-Japan,desktop,Android,failed,10,54,api_gateway,76.21,87,1,yes,sql_injection,100,anomaly
1,2026-04-19 06:08:50.816559,U3829,admin,141.202.123.121,Mumbai-India,mobile,Windows,success,2,139,api_gateway,15.07,6,0,no,normal,16,normal
2,2026-04-19 06:09:06.816559,U2926,admin,41.216.198.169,Pune-India,mobile,Linux,success,1,596,user_data,19.66,7,1,no,normal,32,normal
3,2026-04-19 06:08:57.816559,U3058,employee,41.46.11.1,Berlin-Germany,server,Linux,failed,1,528,db_server,12.41,27,0,no,normal,20,normal
4,2026-04-19 06:09:20.816559,U1295,admin,207.203.180.157,Delhi-India,server,Windows,success,0,83,api_gateway,9.56,8,1,no,normal,25,normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2026-04-19 06:58:33.816559,U6244,admin,235.238.80.33,NY-USA,server,Android,failed,8,8,internal_dashboard,99.97,128,1,yes,sql_injection,100,anomaly
996,2026-04-19 07:31:48.816559,U7838,employee,73.40.208.192,NY-USA,desktop,Android,failed,1,494,internal_dashboard,17.24,7,0,no,normal,11,normal
997,2026-04-19 08:21:44.816559,U8796,employee,238.153.155.35,Mumbai-India,server,iOS,failed,2,320,payment_system,4.45,5,1,no,normal,33,normal
998,2026-04-19 06:25:26.816559,U4454,admin,73.52.106.0,Pune-India,server,iOS,success,1,359,user_data,8.21,8,0,yes,normal,30,normal
999,2026-04-19 07:48:42.816559,U6812,employee,156.4.2.61,Mumbai-India,mobile,Linux,failed,8,45,api_gateway,194.64,104,1,yes,brute_force,100,anomaly

In [20]:
for col in df.select_dtypes(include=['object']).columns:
        le = LabelEncoder()
        df[col] = le.fit_transform(df[col])

In [41]:
import pickle
with open('scaler.pkl','wb') as file1:
    pickle.dump(scaler,file1)

In [21]:
def train_model(df):
    df = preprocess_data(df)

In [23]:
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [24]:
X = scaler.fit_transform(X)

In [25]:
X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )

In [42]:
with open('model.pkl', 'wb') as file2:
    pickle.dump(model,file2)

In [26]:

    model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [28]:
pred = model.predict(X_test)
acc = accuracy_score(y_test, pred)

In [30]:
def detect_anomaly(df):
    df = preprocess_data(df)

In [31]:
    X = scaler.transform(df.iloc[:, :-1])

In [32]:
    preds = model.predict(X)

In [33]:
    df['Prediction'] = preds

In [34]:
def anomaly_kmeans(df):
    df = preprocess_data(df)

In [35]:
    X = scaler.fit_transform(df)

In [37]:
kmeans = KMeans(n_clusters=2, random_state=42)
df['Cluster'] = kmeans.fit_predict(X)

In [40]:
def risk_score(row):
   return np.sum(row) % 100

In [43]:
with open('model.pkl' , 'rb') as file4:  
    m= pickle.load(file4)